### ISSUE TITLE
Client side jitter when moving against an object

### ISSUE THREAD

**Issue by dustingraham** [JoaoBorks/unity-fastpacedmultiplayer#2]
Is it a bug, or reasonable to solve the problem where you are moving against a collider and jitter when you're passing it?

Here's a gfy showing the jitter of the green client.

https://gfycat.com/FlawedYellowHuman

I suspect it is something to do with the agreement and prediction of moving around the object, but it seems pretty significant. I'm simply trying to move through the two objects and adjusting my course slightly with the arrow keys to get around the blocks, and pretty consistently it jitters the moment it can finally pass by.

Edit: And to be clear, on the box, I'm holding the right arrow down the entire time and tapping the down arrow until it gets by. There's a lot of jump/rubberbanding.

**Comment by thatjoaoguy** [comment]
Hello Dustin! Thanks for your feedback, I\`m currently working on the prediction and observation of the objects, so the problem lies there. It\`s still unstable but I`m getting close to solve it

**Comment by NFMynster** [comment]
Hows stuff going @JoaoBorks? :)

**Comment by thatjoaoguy** [comment]
Guys, thanks for your interest! I'm getting very busy on work lately and having trouble to find time to work on this project but I should resume in July. As always any suggestions or contributions are welcome. 

I'll give some updates once I have something working. I have not abandoned the project.

**Comment by felipejfc** [comment]
@NFMynster my team have reviewed everything and we've sent a PR https://github.com/JoaoBorks/unity-fastpacedmultiplayer/pull/3 fixing interpolation, prediction and reconciliation logics

**Comment by NFMynster** [comment]
Awesome, will check it out

**Comment by thatjoaoguy** [comment]
Hello guys, I've just merged #3 and it seems to have solved this issue. Please test and see if the issue persists, otherwise I'll close the thread.
